<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.youdatax.dsp</groupId>
  <artifactId>youdatax-dsp-main-service-http</artifactId>
  <version>0.0.3-SNAPSHOT</version>
  
  <dependencies>
<!--    api(project(":spi:common:http-spi"))-->
      <dependency>
        <groupId>com.yospace.core</groupId> 
        <artifactId>yospace-core-spi-http</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>
<!--    api(project(":spi:common:json-ld-spi"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-spi-json-ld</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    api(project(":spi:common:validator-spi"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>  
        <artifactId>yospace-core-spi-validator</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    api(project(":spi:common:token-spi"))-->
      <dependency>
        <groupId>com.yospace.core</groupId> 
        <artifactId>yospace-core-spi-token</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    api(project(":spi:control-plane:contract-spi"))-->
      <dependency>
        <groupId>com.yospace.controlplane</groupId>
        <artifactId>yospace-control-plane-spi-contract</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    api(project(":spi:control-plane:transfer-spi"))-->
      <dependency>
        <groupId>com.yospace.controlplane</groupId>
        <artifactId>yospace-control-plane-spi-transfer</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    api(project(":extensions:common:json-ld"))
      <dependency>
        <groupId>com.yospace.ext</groupId>
        <artifactId>yospace-ext-type-service-json-ld</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    -->
<!--    api(project(":data-protocols:dsp:dsp-spi"))-->
      <dependency>
        <groupId>com.yospace.dsp</groupId>
        <artifactId>yospace-dsp-core-spi</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    api(project(":data-protocols:dsp:dsp-http-spi"))-->
      <dependency>
        <groupId>com.yospace.dsp</groupId>
        <artifactId>yospace-dsp-core-spi-http</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>
      
<!--    testImplementation(project(":core:common:junit"))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>junit</artifactId>
        <version>0.18.0</version>
      </dependency>    
<!--    testImplementation(project(":core:common:lib:json-ld-lib"))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>json-ld-lib</artifactId>
        <version>0.18.0</version>
      </dependency>    
<!--    testImplementation(project(":extensions:common:http:jersey-core"))  -->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>jersey-core</artifactId>
        <version>0.18.0</version>
      </dependency>   
   </dependencies>    
</project>